Fix JDBC Instant encoder
zio/zio-protoquill pull request #251
Opened 2023-03-10 23:44 UTC by 987Nabil

- Instants don't have time zones.
- Fix small typo.

2023-03-12 03:36 UTC, deusaquilus commented
I'm not sure about this one. Instant doesn't have a timezone but the target column in the DB that it's being encoded to might.  At that point, a timezone is necessary anyway. I'm not exactly sure how it works about but maybe this needs to be tested with a few different DB column-types to see what the most sane behavior is.

2023-03-16 11:26 UTC, 987Nabil commented
I think if your code timestamp has no timezone, but your db has, or the other way around, you just have a bug.
You can't write a JVM Long into a db smallint either.

2023-05-04 16:53 UTC, 987Nabil commented
@deusaquilus any thoughts on my arguments? 🙂

2023-06-24 08:39 UTC, guizmaii requested changes
As discussed on Discord, this change is not retro-compatible, and so it is not the way to go.

@987Nabil, Can you please make the changes we discussed?

2023-08-30 13:33 UTC, closed without merging

2023-10-26 15:01 UTC, guizmaii commented
@987Nabil TIL more things about encoding `Instant` into a DB and it's more complex than it seems. If you're interested, I detailed my learning here: https://github.com/zio/zio-jdbc/pull/171#discussion_r1373311560